Wap 4485 adaptor
spotx/prebid-server pull request #2
Opened 2019-06-10 22:50 UTC by mgloystein

Rebase off master

2019-06-12 19:27 UTC, bluedreamer reviewed
I have more to look at but maybe you can get started on current comments

2019-06-12 19:27 UTC, bluedreamer commented on adapters/spotx/spotx.go
> +	timeCodeComponents := strings.Split(timeDuration, ":")
You might find these useful - these are from the C++ vast unit tests

static std::vector<std::string> invalid_time_strings = {"invalid",
                                                        "0s",
                                                        "00:00",
                                                        "00:00:0",
                                                        "00:0:00",
                                                        "00:00:000",
                                                        "00:000:00",
                                                        "00:00:00.0",
                                                        "00:00:00.00",
                                                        "00:00:00.0000",
                                                        "00:00:00PM"};

static std::vector<std::string> valid_time_strings =
    {"0:00:00", "00:00:00", "00:00:00.000", "000:00:00.000", "123:45:56.789", "9999:99:99.999"};

2019-06-12 19:27 UTC, bluedreamer commented on adapters/spotx/spotx.go
> +	resp, err := ctxhttp.Do(ctx, a.http.Client, httpReq)
This is the request you are sending to spotx right? So a lot of our content is going to be refined on geo/device type - so I wonder if you need this section

   "device":{  
      "h":736,
      "w":414,
      "lmt":0,
      "connectionType":2,
      "make":"Apple",
      "model":"iPhone9,4",
      "os":"iOS",
      "osv":"11.2.6",
      "ua":"Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML,like Gecko) Mobile/15D100",
      "ifa":"EEBBF4EE-3B08-4556-BC3E-CCD3EBB8E4B4",
      "geo":{  
         "country":"NZ",
         "city":"Auckland",
         "zip":"1150"
      },

2019-06-12 19:27 UTC, bluedreamer commented on adapters/spotx/spotx.go
> +	httpReq.Header.Add("Accept", "application/json")
I wonder if we should set a user agent so we can id our own calls
"User-Agent: spotx-prebidderwidget_do_dad"

2019-06-13 17:26 UTC, mgloystein commented on adapters/spotx/spotx.go
> +	httpReq.Header.Add("Accept", "application/json")
Do you have an idea of what a legitimate value should be for this?

2019-06-13 17:30 UTC, mgloystein commented on adapters/spotx/spotx.go
> +	resp, err := ctxhttp.Do(ctx, a.http.Client, httpReq)
_Hopefully_ all that information will already be in the request and correctly massaged into the Open RTB request we are making to ourselves. `Call` calls this method after calling `adapters.MakeOpenRTBGeneric`, which is meant to transform the *prebid request* into an *ortb request*. Device is part of both specs so I assume that translation is done in that call.

2019-06-13 17:32 UTC, mgloystein commented on adapters/spotx/spotx.go
> +	timeCodeComponents := strings.Split(timeDuration, ":")
I'll change it to a float64 and increase my slice capacity to 16.

2019-06-13 18:49 UTC, bluedreamer commented on adapters/spotx/spotx.go
> +	httpReq.Header.Add("Accept", "application/json")
It might be nice to identify, so how about "spotx_prebid_server 1.0" or similar

2019-07-19 17:24 UTC, strider820 commented
I'll let others leave comments for things I might have missed, but from my perspective, it seems like it'd do what I'd expect for prebid server

2019-08-02 20:06 UTC, thomasrmielke reviewed
It seems like this adapter is sending a lot of fields that are not currently supported by SpotX. It will not cause an error in the request, but the extra fields will be ignored.

Also, it was a little difficult to trace the flow of the code. I expected to see the bids constructed hierarchically, but it didn't seem to be organized that way. That being said, I'm not familiar with a lot of the syntax in Go, so that may be contributing to it.

Have you tried connecting the requests generated here with a test SpotX server to validate the responses?

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +	if config.ChannelID == 0 {
Are you checking for '0' here specifically because it's a default value?

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +	httpReq.Header.Add("Accept", "application/json")
SpotMarket needs the user agent accurately reflect the device that the ad will run on. We use it for audience identification, device targeting, etc. I would suggest another method for indicating prebid server calls (maybe supply chain?)

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +					cat = bid.Cat[0]
Why only the first element in bid.Cat?

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +	for i := 0; i < len(vastResponse); i++ { // Iterate over every character
Why are you writing an xml parser here? Are there no available libs to parse XML?

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +		if imp.ID == impId {
I don't know if this is a realistic request, but what if there are multiple objects specified? The spec doesn't indicate that the values are mutually exclusive. This might be a question for product.

Also, there is an implicit precedence for choosing the media type. Is that intentionally? E.g., video will always be choosen over audio?

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +		ortbReq.Imp[i].BidFloorCur = param.Currency
BidFloorCur is not currently supported by SpotX, FYI. There are some internal SpotX docs that indicate which parts of OpenRTB are supported by SpotX.

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +			ortbReq.Imp[1].Video.BoxingAllowed = int8(1)
Not supported.

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +			ortbReq.Imp[i].Ext = kvpToExt(param.KVP)
Looking at the code and docs, I don't believe KVPs are supported this way either.

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +	ortbReq.BCat = param.BlackList.Category
Not supported.

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +	if len(param.WhiteList.Seat) > 0 {
Not supported.

2019-08-02 20:06 UTC, thomasrmielke commented on adapters/spotx/spotxtests/exemplary/ortb_2.3_video.json
> +        "ortb_version": "2.3",
This isn't currently supported.

2019-08-02 20:07 UTC, thomasrmielke commented
There are several internal SpotX confluence pages outlining what is supported on the pORTB endpoint and what isn't. Let me know if you'd like those pages.

2019-08-12 21:11 UTC, mgloystein commented on adapters/spotx/spotx.go
> +	if config.ChannelID == 0 {
Yes

2019-08-12 21:12 UTC, mgloystein commented on adapters/spotx/spotx.go
> +					cat = bid.Cat[0]
I wasn't able to find a primary category in our result but the object passed to the decision point requires there be a primary.

2019-08-12 21:14 UTC, mgloystein commented on adapters/spotx/spotx.go
> +	for i := 0; i < len(vastResponse); i++ { // Iterate over every character
I'm not fully parsing the xml, I only care about a single value and this has to be fast.

2019-08-12 21:16 UTC, mgloystein commented on adapters/spotx/spotx.go
> +		ortbReq.Imp[i].BidFloorCur = param.Currency
As long as it doesn't break things and there's ever a possibility of it being added, I'd like to keep it.

2019-08-12 21:17 UTC, mgloystein commented on adapters/spotx/spotx.go
> +			ortbReq.Imp[1].Video.BoxingAllowed = int8(1)
Will it break things? Might it be supported in the future?

2019-08-12 21:18 UTC, mgloystein commented on adapters/spotx/spotx.go
> +			ortbReq.Imp[i].Ext = kvpToExt(param.KVP)
How are they supported?

2019-08-12 21:24 UTC, mgloystein commented on adapters/spotx/spotx.go
> +		if imp.ID == impId {
I _think_ an impression can only have one type and the requester would have to specify another impression if they wanted a bid for a different type.

2019-08-30 18:57 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +					cat = bid.Cat[0]
Ok

2019-08-30 18:57 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +	for i := 0; i < len(vastResponse); i++ { // Iterate over every character
Ok

2019-08-30 19:00 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +		if imp.ID == impId {
Ok, any reason for the implicit precedence chosen here? Video over audio?

2019-08-30 19:01 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +			ortbReq.Imp[1].Video.BoxingAllowed = int8(1)
Will not break things. Just suggesting that you could limit the scope of your work to just the supported fields (reduces our bandwidth too).

2019-08-30 19:06 UTC, thomasrmielke approved these changes

2019-08-30 19:06 UTC, thomasrmielke commented on adapters/spotx/spotx.go
> +			ortbReq.Imp[i].Ext = kvpToExt(param.KVP)
Per our docs, in the video ext field (not the imp.ext). See https://confluence.spotxchange.com/display/byndocspotx/SpotMarket+Publisher+OpenRTB+Endpoint+Support

2019-08-30 19:10 UTC, thomasrmielke requested changes
Just a few minor questions remain. Outstanding issues would be the custom kvps and user agent.

2019-09-04 22:08 UTC, thomasrmielke approved these changes

2025-11-21 15:10 UTC, closed without merging